[repair]
maxmemory = "32G"
cuda = true
type = "regression"

[repair.model]
model = "networks/dave/model.onnx"

[repair.data]
dataset = "UdacityDriving"
batchsize = 256

[repair.data.transform]
bgr = true
mean = [103.939, 116.779, 123.68]
max_value = 255.0

[repair.data.train]
path = "artifacts/udacity.sdc.100/training"
shuffle = true

[repair.data.validation]
path = "artifacts/udacity.sdc.100/validation"
shuffle = false
